# Generated by Django 3.2.9 on 2021-12-06 18:45

import autoslug.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(help_text='Digite o título completo do livro.', max_length=150, verbose_name='Título do livro')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('description', models.TextField(blank=True)),
                ('cover', stdimage.models.StdImageField(blank=True, help_text='Faça upload da imagem de capa', upload_to='cover_imgs/', verbose_name='Imagem de capa')),
                ('is_published', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(blank=True, related_name='books', to='book.Category')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
